default: &default
  adapter: postgresql
  encoding: UTF8
  host: <%= ENV.fetch("DATABASE_HOST") { "localhost" } %>
  user: <%= ENV.fetch("DATABASE_USERNAME") { "postgres" } %>
  password: <%= ENV.fetch("DATABASE_PASSWORD") { "postgres" } %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: chatbot_interview_development

test:
  <<: *default
  database: chatbot_interview_test

#
production:
  <<: *default
  database: chatbot_interview_production
  username: chatbot_interview
  password: <%= ENV["CHATBOT_INTERVIEW_DATABASE_PASSWORD"] %>
